######################################################################
# Automatically generated by qmake (1.07a) Fri Apr 21 06:07:33 2006
######################################################################

TARGET=ADDOFFW
DESTDIR+=/opt/olfix/bin
TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += frmaddoffert.ui.h
INTERFACES += frmaddoffert.ui
SOURCES += main.cpp
