######################################################################
# Automatically generated by qmake (1.04a) Mon Aug 18 11:50:14 2003
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += frmlevfaktattbetala.ui.h
INTERFACES += frmlevfaktattbetala.ui
SOURCES += main.cpp
