######################################################################
# Automatically generated by qmake (1.04a) Sun Nov 14 05:31:35 2004
######################################################################

TARGET=ATTBETW
DESTDIR+=/home/jan/Utveckling/OLFIX/bin
TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += frmlevfaktattbetala.ui.h
INTERFACES += frmlevfaktattbetala.ui
SOURCES += main.cpp
