######################################################################
# Automatically generated by qmake (1.04a) Sun Nov 14 07:10:38 2004
######################################################################

TARGET=LSTFORW
DESTDIR+=/opt/olfix/bin
TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += frmlistforetag.ui.h
INTERFACES += frmlistforetag.ui
SOURCES += main.cpp
