######################################################################
# Automatically generated by qmake (1.04a) Thu Nov 11 06:05:07 2004
######################################################################

TARGET=LSTFORW
DESTDIR+=/home/jan/Utveckling/OLFIX/bin
TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += frmlistforetag.ui.h
INTERFACES += frmlistforetag.ui
SOURCES += main.cpp
