######################################################################
# Automatically generated by qmake (1.04a) Fri Nov 12 13:33:01 2004
######################################################################

TARGET=ADDLEVW
DESTDIR+=/home/jan/Utveckling/OLFIX/bin
TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += frmaddlev.ui.h
INTERFACES += frmaddlev.ui
SOURCES += main.cpp
