######################################################################
# Automatically generated by qmake (1.04a) Mon Jun 9 08:25:59 2003
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += frmaddlev.ui.h
INTERFACES += frmaddlev.ui
SOURCES += main.cpp
