######################################################################
# Automatically generated by qmake (1.04a) Thu Nov 11 06:35:26 2004
######################################################################

TARGET=ADDFNCW
DESTDIR+=/home/jan/Utveckling/OLFIX/bin
TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += frmaddfnc.ui.h
INTERFACES += frmaddfnc.ui
SOURCES += main.cpp
