######################################################################
# Automatically generated by qmake (1.03a) Wed Apr 2 06:39:11 2003
######################################################################

TEMPLATE = app

# Input
HEADERS += frmaddfnc.ui.h
INTERFACES += frmaddfnc.ui
SOURCES += main.cpp
