######################################################################
# Automatically generated by qmake (1.04a) Sun Nov 27 07:33:21 2005
######################################################################

TARGET=SRCHARW
DESTDIR+=/opt/olfix/bin
TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += frmsoekartikel.ui.h
INTERFACES += frmsoekartikel.ui
SOURCES += main.cpp
