######################################################################
# Automatically generated by qmake (1.04a) Wed Aug 6 08:00:01 2003
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += frmdspkonto.ui.h
INTERFACES += frmdspkonto.ui
SOURCES += main.cpp
