######################################################################
# Automatically generated by qmake (1.04a) Sat Nov 13 15:22:54 2004
######################################################################

TARGET=DSPKTOW
DESTDIR+=/home/jan/Utveckling/OLFIX/bin
TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += frmdspkonto.ui.h
INTERFACES += frmdspkonto.ui
SOURCES += main.cpp
