######################################################################
# Automatically generated by qmake (1.03a) Tue Apr 15 08:19:51 2003
######################################################################

TEMPLATE = app
CONFIG -= moc

# Input
INTERFACES += frmdspftgdata.ui
SOURCES += main.cpp
