######################################################################
# Automatically generated by qmake (1.03a) Tue Apr 29 07:08:12 2003
######################################################################

TEMPLATE = app

# Input
HEADERS += frmdspftgdata.ui.h
INTERFACES += frmdspftgdata.ui
SOURCES += main.cpp
