######################################################################
# Automatically generated by qmake (1.04a) Sat Nov 13 15:08:28 2004
######################################################################

TARGET=DSPFTGW
DESTDIR+=/opt/olfix/bin
TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += frmdspftgdata.ui.h
INTERFACES += frmdspftgdata.ui
SOURCES += main.cpp
