######################################################################
# Automatically generated by qmake (1.04a) Fri Nov 12 20:24:58 2004
######################################################################

TARGET=BALRPTW
DESTDIR+=/home/jan/Utveckling/OLFIX/bin
TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += frmbalansrapport.ui.h
INTERFACES += frmbalansrapport.ui
SOURCES += main.cpp
