######################################################################
# Automatically generated by qmake (1.04a) Fri Mar 19 06:53:14 2004
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += frmbalansrapport.ui.h
INTERFACES += frmbalansrapport.ui
SOURCES += main.cpp
