######################################################################
# Automatically generated by qmake (1.04a) Thu Nov 11 11:11:25 2004
######################################################################

TARGET=OLFIXW
DESTDIR+=/home/jan/Development/OLFIX/bin
TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += frmolfix.ui.h
INTERFACES += frmolfix.ui
SOURCES += main.cpp
