######################################################################
# Automatically generated by qmake (1.03a) Wed Feb 5 06:19:57 2003
######################################################################

TEMPLATE = app

# Input
HEADERS += frmolfix.ui.h
INTERFACES += frmolfix.ui
SOURCES += main.cpp
