######################################################################
# Automatically generated by qmake (1.04a) Sat Nov 15 07:31:44 2003
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += frmdspartikelgrundata.ui.h
INTERFACES += frmdspartikelgrundata.ui
SOURCES += main.cpp
