######################################################################
# Automatically generated by qmake (1.04a) Sat Nov 13 13:16:26 2004
######################################################################

TARGET=DSPARW
DESTDIR+=/opt/olfix/bin
TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += frmdspartikelgrundata.ui.h
INTERFACES += frmdspartikelgrundata.ui
SOURCES += main.cpp
