######################################################################
# Automatically generated by qmake (1.04a) Sun Nov 14 05:25:04 2004
######################################################################

TARGET=RPTKTOW
DESTDIR+=/opt/olfix/bin
TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += ktorapport.ui.h
INTERFACES += ktorapport.ui
SOURCES += main.cpp
