######################################################################
# Automatically generated by qmake (1.03a) Sat Mar 8 10:01:39 2003
######################################################################

TEMPLATE = app

# Input
HEADERS += ktorapport.ui.h
INTERFACES += ktorapport.ui
SOURCES += main.cpp
