######################################################################
# Automatically generated by qmake (1.04a) Mon Feb 9 07:18:05 2004
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += frmlistlevvillkor.ui.h
INTERFACES += frmlistlevvillkor.ui
SOURCES += main.cpp
