######################################################################
# Automatically generated by qmake (1.04a) Mon Nov 15 05:16:59 2004
######################################################################

TARGET=LSTLEVVW
DESTDIR+=/opt/olfix/bin
TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += frmlistlevvillkor.ui.h
INTERFACES += frmlistlevvillkor.ui
SOURCES += main.cpp
