######################################################################
# Automatically generated by qmake (1.03a) Tue Jan 21 08:02:20 2003
######################################################################

TEMPLATE = app

# Input
HEADERS += frmchguser.ui.h
INTERFACES += frmchguser.ui
SOURCES += main.cpp
