######################################################################
# Automatically generated by qmake (1.04a) Sat Nov 13 08:48:10 2004
######################################################################

TARGET=CHGUSRW
DESTDIR+=/home/jan/Utveckling/OLFIX/bin
TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += frmchguser.ui.h
INTERFACES += frmchguser.ui
SOURCES += main.cpp
