######################################################################
# Automatically generated by qmake (1.04a) Wen Mars 22 08:11:09 2006
######################################################################

TARGET=LSTPGMW
DESTDIR+=/opt/olfix/bin
TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += frmlistprogram.ui.h
INTERFACES += frmlistprogram.ui
SOURCES += main.cpp
