######################################################################
# Automatically generated by qmake (1.04a) Mon Nov 29 14:04:31 2004
######################################################################

TARGET=ADDPKDW
DESTDIR+=/opt/olfix/bin
TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += frmaddprodkod.ui.h
INTERFACES += frmaddprodkod.ui
SOURCES += main.cpp
