######################################################################
# Automatically generated by qmake (1.04a) Wed Nov 23 06:09:03 2005
######################################################################

TARGET=LSTTXTW
DESTDIR+=/home/jan/Utveckling/OLFIX/bin
TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += frmlisttextreg.ui.h
INTERFACES += frmlisttextreg.ui
SOURCES += main.cpp
