######################################################################
# Automatically generated by qmake (1.07a) Tue Apr 11 11:36:03 2006
######################################################################

TARGET=LSTTXTW
DESTDIR+=/home/jan/Development/OLFIX/bin
TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += frmlisttextreg.ui.h
INTERFACES += frmlisttextreg.ui
SOURCES += main.cpp
