######################################################################
# Automatically generated by qmake (1.04a) Mon Dec 8 06:58:14 2003
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += frmaddbest.ui.h
INTERFACES += frmaddbest.ui
SOURCES += main.cpp
