######################################################################
# Automatically generated by qmake (1.04a) Thu Nov 11 06:23:05 2004
######################################################################

TARGET=ADDINKW
DESTDIR+=/home/jan/Development/OLFIX/bin
TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += frmaddbest.ui.h
INTERFACES += frmaddbest.ui
SOURCES += main.cpp
