######################################################################
# Automatically generated by qmake (1.04a) Fri Nov 12 13:12:49 2004
######################################################################

TARGET=ADDKSTW
DESTDIR+=/home/jan/Utveckling/OLFIX/bin
TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += frmaddkstalle.ui.h
INTERFACES += frmaddkstalle.ui
SOURCES += main.cpp
