######################################################################
# Automatically generated by qmake (1.03a) Sat Feb 22 06:20:26 2003
######################################################################

TEMPLATE = app

# Input
HEADERS += frmaddkstalle.ui.h
INTERFACES += frmaddkstalle.ui
SOURCES += main.cpp
