######################################################################
# Automatically generated by qmake (1.04a) Sat Nov 13 06:26:15 2004
######################################################################

TARGET=BYTFTGW
DESTDIR+=/home/jan/Utveckling/OLFIX/bin
TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += frmbytforetag.ui.h
INTERFACES += frmbytforetag.ui
SOURCES += main.cpp
