######################################################################
# Automatically generated by qmake (1.04a) Sun Oct 19 07:03:59 2003
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += frmbytforetag.ui.h
INTERFACES += frmbytforetag.ui
SOURCES += main.cpp
