######################################################################
# Automatically generated by qmake (1.04a) Fri Nov 12 13:28:38 2004
######################################################################

TARGET=ADDLPLW
DESTDIR+=/opt/olfix/bin
TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += frmaddlagerplats.ui.h
INTERFACES += frmaddlagerplats.ui
SOURCES += main.cpp
