######################################################################
# Automatically generated by qmake (1.04a) Thu Oct 30 11:57:18 2003
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += frmaddlagerplats.ui.h
INTERFACES += frmaddlagerplats.ui
SOURCES += main.cpp
TARGET = $(OLFIXBIN)/ADDLPLW