######################################################################
# Automatically generated by qmake (1.04a) Wed Jun 11 05:30:48 2003
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += frmchglev.ui.h
INTERFACES += frmchglev.ui
SOURCES += main.cpp
