######################################################################
# Automatically generated by qmake (1.04a) Sat Nov 13 08:44:54 2004
######################################################################

TARGET=CHGLEVW
DESTDIR+=/home/jan/Utveckling/OLFIX/bin
TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += frmchglev.ui.h
INTERFACES += frmchglev.ui
SOURCES += main.cpp
