######################################################################
# Automatically generated by qmake (1.04a) Sat Nov 13 08:52:35 2004
######################################################################

TARGET=CHGVALW
DESTDIR+=/opt/olfix/bin
TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += frmchgvaluta.ui.h
INTERFACES += frmchgvaluta.ui
SOURCES += main.cpp
