######################################################################
# Automatically generated by qmake (1.03a) Fri Feb 21 09:41:30 2003
######################################################################

TEMPLATE = app

# Input
HEADERS += frmchgvaluta.ui.h
INTERFACES += frmchgvaluta.ui
SOURCES += main.cpp
