######################################################################
# Automatically generated by qmake (1.03a) Wed Jan 15 06:21:39 2003
######################################################################

TEMPLATE = app

# Input
HEADERS += frmaddkonto.ui.h
INTERFACES += frmaddkonto.ui
SOURCES += main.cpp
