######################################################################
# Automatically generated by qmake (1.04a) Thu Nov 11 06:37:25 2004
######################################################################

TARGET=ADDKTOW
DESTDIR+=/opt/olfix/bin
TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += frmaddkonto.ui.h
INTERFACES += frmaddkonto.ui
SOURCES += main.cpp
