######################################################################
# Automatically generated by qmake (1.04a) Mon Feb 16 12:09:04 2004
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += helpwindow.h
SOURCES += helpwindow.cpp main.cpp
