######################################################################
# Automatically generated by qmake (1.04a) Sun Nov 14 05:15:32 2004
######################################################################

TARGET=OLFIXHLP
DESTDIR+=/home/jan/Utveckling/OLFIX/bin
TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += helpwindow.h
SOURCES += helpwindow.cpp main.cpp
