######################################################################
# Automatically generated by qmake (1.07a) Tue Dec 5 07:16:22 2006
######################################################################

TARGET=TOTRGTW
DESTDIR+=/home/jan/Development/OLFIX/bin
TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += frmtotalrights.ui.h
INTERFACES += frmtotalrights.ui
SOURCES += main.cpp
