######################################################################
# Automatically generated by qmake (1.04a) Tue Oct 28 15:56:13 2003
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += frmaddartikel.ui.h
INTERFACES += frmaddartikel.ui
SOURCES += main.cpp
