######################################################################
# Automatically generated by qmake (1.04a) Thu Nov 11 06:14:30 2004
######################################################################

TARGET=ADDARW
DESTDIR+=/home/jan/Utveckling/OLFIX/bin
TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += frmaddartikel.ui.h
INTERFACES += frmaddartikel.ui
SOURCES += main.cpp
