######################################################################
# Automatically generated by qmake (1.04a) Mon Feb 9 06:38:06 2004
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += frmaddlevsett.ui.h
INTERFACES += frmaddlevsett.ui
SOURCES += main.cpp
