######################################################################
# Automatically generated by qmake (1.04a) Fri Nov 12 15:36:51 2004
######################################################################

TARGET=ADDLEVSW
DESTDIR+=/opt/olfix/bin
TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += frmaddlevsett.ui.h
INTERFACES += frmaddlevsett.ui
SOURCES += main.cpp
