######################################################################
# Automatically generated by qmake (1.04a) Sat Nov 13 11:25:19 2004
######################################################################

TARGET=DELRGTW
DESTDIR+=/opt/olfix/bin
TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += frmdelrights.ui.h
INTERFACES += frmdelrights.ui
SOURCES += main.cpp
