######################################################################
# Automatically generated by qmake (1.03a) Sat Feb 22 17:22:10 2003
######################################################################

TEMPLATE = app

# Input
HEADERS += frmdelrights.ui.h
INTERFACES += frmdelrights.ui
SOURCES += main.cpp
