######################################################################
# Automatically generated by qmake (1.04a) Mon Dec 29 14:37:41 2003
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += frmlstink.ui.h
INTERFACES += frmlstink.ui
SOURCES += main.cpp
