######################################################################
# Automatically generated by qmake (1.04a) Sun Nov 14 07:03:22 2004
######################################################################

TARGET=LSTINKW
DESTDIR+=/home/jan/Utveckling/OLFIX/bin
TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += frmlstink.ui.h
INTERFACES += frmlstink.ui
SOURCES += main.cpp
