######################################################################
# Automatically generated by qmake (1.04a) Fri Dec 31 12:15:32 2004
######################################################################

TARGET=LSTFTGW
DESTDIR+=/opt/olfix/bin
TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += frmlistftgdata.ui.h
INTERFACES += frmlistftgdata.ui
SOURCES += main.cpp
