######################################################################
# Automatically generated by qmake (1.04a) Thu Aug 21 08:18:06 2003
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += frmsaldolista.ui.h
INTERFACES += frmsaldolista.ui
SOURCES += main.cpp
