######################################################################
# Automatically generated by qmake (1.04a) Mon Nov 15 05:47:12 2004
######################################################################

TARGET=SDOLISW
DESTDIR+=/opt/olfix/bin
TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += frmsaldolista.ui.h
INTERFACES += frmsaldolista.ui
SOURCES += main.cpp
