######################################################################
# Automatically generated by qmake (1.07a) Sat Jan 28 04:54:54 2006
######################################################################

TARGET=CHGPRISW
DESTDIR+=/opt/olfix/bin
TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += frmloadprices.ui.h
INTERFACES += frmloadprices.ui
SOURCES += main.cpp
