######################################################################
# Automatically generated by qmake (1.04a) Sun Dec 4 06:45:17 2005
######################################################################

TARGET=KUFAKTBW
DESTDIR+=/opt/olfix/bin
TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += frmkundfakturabetald.ui.h
INTERFACES += frmkundfakturabetald.ui
SOURCES += main.cpp
