######################################################################
# Automatically generated by qmake (1.03a) Wed Jan 29 10:45:37 2003
######################################################################

TEMPLATE = app
CONFIG -= moc

# Input
INTERFACES += frmchgkonto.ui
SOURCES += main.cpp
