######################################################################
# Automatically generated by qmake (1.04a) Sat Nov 13 08:37:48 2004
######################################################################

TARGET=CHGKTOW
DESTDIR+=/home/jan/Utveckling/OLFIX/bin
TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += frmchgkonto.ui.h
INTERFACES += frmchgkonto.ui
SOURCES += main.cpp
