######################################################################
# Automatically generated by qmake (1.03a) Sat Jan 11 12:11:41 2003
######################################################################

TEMPLATE = app

# Input
HEADERS += frmadduser.ui.h
INTERFACES += frmadduser.ui
SOURCES += main.cpp
