######################################################################
# Automatically generated by qmake (1.04a) Fri Nov 12 17:15:59 2004
######################################################################

TARGET=ADDUSRW
DESTDIR+=/opt/olfix/bin
TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += frmadduser.ui.h
INTERFACES += frmadduser.ui
SOURCES += main.cpp
