######################################################################
# Automatically generated by qmake (1.04a) Thu Jun 19 06:54:26 2003
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += frmlevfakt.ui.h
INTERFACES += frmlevfakt.ui
SOURCES += main.cpp
