######################################################################
# Automatically generated by qmake (1.04a) Sun Nov 14 05:35:09 2004
######################################################################

TARGET=LEVFAKTW
DESTDIR+=/opt/olfix/bin
TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += frmlevfakt.ui.h
INTERFACES += frmlevfakt.ui
SOURCES += main.cpp
