######################################################################
# Automatically generated by qmake (1.04a) Sat Nov 13 06:21:28 2004
######################################################################

TARGET=CHGBETVW
DESTDIR+=/opt/olfix/bin
TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += frmchgbetalvillkor.ui.h
INTERFACES += frmchgbetalvillkor.ui
SOURCES += main.cpp
