######################################################################
# Automatically generated by qmake (1.04a) Fri Nov 28 06:29:38 2003
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += frmchgbetalvillkor.ui.h
INTERFACES += frmchgbetalvillkor.ui
SOURCES += main.cpp
