######################################################################
# Automatically generated by qmake (1.04a) Sun Nov 14 08:14:32 2004
######################################################################

TARGET=LSTKTOW
DESTDIR+=/home/jan/Utveckling/OLFIX/bin
TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += frmlistkonto.ui.h
INTERFACES += frmlistkonto.ui
SOURCES += main.cpp
