######################################################################
# Automatically generated by qmake (1.03a) Tue Jan 14 06:29:01 2003
######################################################################

TEMPLATE = app

# Input
HEADERS += frmlistkonto.ui.h
INTERFACES += frmlistkonto.ui
SOURCES += main.cpp
