######################################################################
# Automatically generated by qmake (1.04a) Sat Apr 10 06:57:53 2004
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += frmdagbok.ui.h
INTERFACES += frmdagbok.ui
SOURCES += main.cpp
