######################################################################
# Automatically generated by qmake (1.04a) Sat Nov 13 11:21:41 2004
######################################################################

TARGET=DAGBOKW
DESTDIR+=/opt/olfix/bin
TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += frmdagbok.ui.h
INTERFACES += frmdagbok.ui
SOURCES += main.cpp
