######################################################################
# Automatically generated by qmake (1.04a) Mon Nov 15 05:40:13 2004
######################################################################

TARGET=PRTINKW
DESTDIR+=/opt/olfix/bin
TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += prtink.ui.h
INTERFACES += prtink.ui
SOURCES += main.cpp
