######################################################################
# Automatically generated by qmake (1.04a) Fri Jan 30 06:07:38 2004
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += prtink.ui.h
INTERFACES += prtink.ui
SOURCES += main.cpp
