######################################################################
# Automatically generated by qmake (1.04a) Thu Nov 11 06:28:47 2004
######################################################################

TARGET=ADDFORW
DESTDIR+=/home/jan/Utveckling/OLFIX/bin
TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += frmaddforetag.ui.h
INTERFACES += frmaddforetag.ui
SOURCES += main.cpp
