######################################################################
# Automatically generated by qmake (1.04a) Tue Nov 9 07:21:31 2004
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += frmaddforetag.ui.h
INTERFACES += frmaddforetag.ui
SOURCES += main.cpp
TARGET = $(OLFIXBIN)/ADDFORW
