######################################################################
# Automatically generated by qmake (1.04a) Sat Nov 13 15:28:58 2004
######################################################################

TARGET=DSPKUW
DESTDIR+=/home/jan/Utveckling/OLFIX/bin
TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += frmdspkund.ui.h
INTERFACES += frmdspkund.ui
SOURCES += main.cpp
