######################################################################
# Automatically generated by qmake (1.04a) Thu Oct 2 08:43:42 2003
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += frmdspkund.ui.h
INTERFACES += frmdspkund.ui
SOURCES += main.cpp
