######################################################################
# Automatically generated by qmake (1.04a) Fri Nov 12 17:02:13 2004
######################################################################

TARGET=ADDRGTW
DESTDIR+=/home/jan/Utveckling/OLFIX/bin
TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += frmaddright.ui.h
INTERFACES += frmaddright.ui
SOURCES += main.cpp
