######################################################################
# Automatically generated by qmake (1.03a) Thu Jan 9 06:33:46 2003
######################################################################

TEMPLATE = app

# Input
HEADERS += frmaddright.ui.h
INTERFACES += frmaddright.ui
SOURCES += main.cpp
