######################################################################
# Automatically generated by qmake (1.04a) Mon Nov 15 05:28:15 2004
######################################################################

TARGET=LSTUSRW
DESTDIR+=/opt/olfix/bin
TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += frmlistuser.ui.h
INTERFACES += frmlistuser.ui
SOURCES += main.cpp
