######################################################################
# Automatically generated by qmake (1.03a) Tue Dec 31 07:24:06 2002
######################################################################

TEMPLATE = app

# Input
HEADERS += getuser.h
INTERFACES += frmlistuser.ui
SOURCES += main.cpp
