######################################################################
# Automatically generated by qmake (1.04a) Mon April 25 06:40:13 2005
######################################################################

TARGET=PLCHGW
DESTDIR+=/opt/olfix/bin
TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += chgplkuord.ui.h
INTERFACES += chgplkuord.ui
SOURCES += main.cpp
