######################################################################
# Automatically generated by qmake (1.04a) Wen Feb 15 07:50:26 2006
######################################################################

TARGET=CHGOFFW
DESTDIR+=/opt/olfix/bin

# Input

TEMPLATE	= app
LANGUAGE	= C++

INCLUDEPATH	+= .

HEADERS	+= frmchgoffert.ui.h

SOURCES	+= main.cpp

FORMS	= frmchgoffert.ui

