######################################################################
# Automatically generated by qmake (1.04a) Sat Nov 13 08:41:03 2004
######################################################################

TARGET=CHGKUW
DESTDIR+=/home/jan/Utveckling/OLFIX/bin
TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += frmchgkund.ui.h
INTERFACES += frmchgkund.ui
SOURCES += main.cpp
