######################################################################
# Automatically generated by qmake (1.04a) Fri Oct 3 13:09:05 2003
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += frmchgkund.ui.h
INTERFACES += frmchgkund.ui
SOURCES += main.cpp
