######################################################################
# Automatically generated by qmake (1.04a) Thu Oct 9 07:01:41 2003
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += frmchgkund.ui.h
INTERFACES += frmchgkund.ui
SOURCES += main.cpp
