######################################################################
# Automatically generated by qmake (1.03a) Sun Feb 23 07:03:19 2003
######################################################################

TEMPLATE = app

# Input
HEADERS += frmdspkstalle.ui.h
INTERFACES += frmdspkstalle.ui
SOURCES += main.cpp
