######################################################################
# Automatically generated by qmake (1.04a) Sat Nov 13 15:26:13 2004
######################################################################

TARGET=DSPKSTW
DESTDIR+=/home/jan/Utveckling/OLFIX/bin
TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += frmdspkstalle.ui.h
INTERFACES += frmdspkstalle.ui
SOURCES += main.cpp
