######################################################################
# Automatically generated by qmake (1.04a) Sun Nov 14 07:07:10 2004
######################################################################

TARGET=LSTBETVW
DESTDIR+=/opt/olfix/bin
TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += frmlistbetalvillkor.ui.h
INTERFACES += frmlistbetalvillkor.ui
SOURCES += main.cpp
