######################################################################
# Automatically generated by qmake (1.04a) Sat Nov 22 06:18:17 2003
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += frmlistbetalvillkor.ui.h
INTERFACES += frmlistbetalvillkor.ui
SOURCES += main.cpp
