######################################################################
# Automatically generated by qmake (1.04a) Fri Nov 12 15:40:15 2004
######################################################################

TARGET=ADDLEVVW
DESTDIR+=/opt/olfix/bin
TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += frmaddlevvillkor.ui.h
INTERFACES += frmaddlevvillkor.ui
SOURCES += main.cpp
