######################################################################
# Automatically generated by qmake (1.04a) Sun Feb 8 12:32:02 2004
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += frmaddlevvillkor.ui.h
INTERFACES += frmaddlevvillkor.ui
SOURCES += main.cpp
