######################################################################
# Automatically generated by qmake (1.04a) Tue Oct 7 07:17:27 2003
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += frmlistkund.ui.h
INTERFACES += frmlistkund.ui
SOURCES += main.cpp
