######################################################################
# Automatically generated by qmake (1.04a) Sun Nov 14 08:58:38 2004
######################################################################

TARGET=LSTKUW
DESTDIR+=/home/jan/Utveckling/OLFIX/bin
TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += frmlistkund.ui.h
INTERFACES += frmlistkund.ui
SOURCES += main.cpp
