######################################################################
# Automatically generated by qmake (1.04a) Sun Dec 5 05:46:17 2004
######################################################################

TARGET=DSPBARW
DESTDIR+=/opt/olfix/bin
TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += frmdspbar.ui.h
INTERFACES += frmdspbar.ui
SOURCES += main.cpp
