######################################################################
# Automatically generated by qmake (1.07a) Sun Nov 19 11:55:27 2006
######################################################################

TARGET=PRTOFFW
DESTDIR+=/home/jan/Development/OLFIX/bin
TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += frmprtoffert.ui.h
INTERFACES += frmprtoffert.ui
SOURCES += main.cpp
