######################################################################
# Automatically generated by qmake (1.04a) Mon April 05 06:40:13 2005
######################################################################

TARGET=FSORDW
DESTDIR+=/opt/olfix/bin
TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += prtfoljesedel.ui.h
INTERFACES += prtfoljesedel.ui
SOURCES += main.cpp
