use olfix;
#ALTER TABLE INKREG ADD ORDERSUMMA DECIMAL(10,2);
ALTER TABLE INKREG MODIFY BESTTYP ENUM('N','D','I','L','A');
use olfixtst;
#ALTER TABLE INKREG ADD ORDERSUMMA DECIMAL(10,2);
ALTER TABLE INKREG MODIFY BESTTYP ENUM('N','D','I','L','A');






