use olfix;
create table INKRADREG(
INKORDNR VARCHAR(10) not null,
INKORDRADNR INT(4)not null,
ARTIKLENR VARCHAR(30),
ENHET VARCHAR(5),
BESTANTAL DECIMAL(10,2),
LEVERERAT DECIMAL(10,2),
RESTNOTERAT DECIMAL(10,2),
INKPRIS DECIMAL(10,2),
LEVDATUMRAD DATE,
TORDNR INT(6),
OPNR INT(6)
);
alter table INKRADREG ADD PRIMARY KEY (INKORDNR,INKORDRADNR);
use olfixtst;
create table INKRADREG(
INKORDNR VARCHAR(10) not null,
INKORDRADNR INT(4)not null,
ARTIKLENR VARCHAR(30),
ENHET VARCHAR(5),
BESTANTAL DECIMAL(10,2),
LEVERERAT DECIMAL(10,2),
RESTNOTERAT DECIMAL(10,2),
INKPRIS DECIMAL(10,2),
LEVDATUMRAD DATE,
TORDNR INT(6),
OPNR INT(6)
);
alter table INKRADREG ADD PRIMARY KEY (INKORDNR,INKORDRADNR);
