use olfix;
create table LAGERSTELLEREG(
ARLAGST		VARCHAR(1)  not null,
ARTIKELNR	VARCHAR(30) not null,
ARLAGHYLLA	VARCHAR(10),
ARLAGSALDO	DECIMAL(10,2),
ARINVGRP	VARCHAR(3),
ARABC		VARCHAR(2),
ARVALUTA	VARCHAR(3),
ARIPRIS		DECIMAL(10,2),
ARIKVANT0	DECIMAL(10,2),
ARIKVANT1	DECIMAL(10,2),
ARIKVANT2	DECIMAL(10,2),
ARKALKPRIS	DECIMAL(10,2),
ARBESTKVANT	DECIMAL(10,2),
ARBESTPUNKT	DECIMAL(10,2)
);
use olfix;
alter table LAGERSTELLEREG ADD PRIMARY KEY (ARTIKELNR,ARLAGST);
use olfixtst;
create table LAGERSTELLEREG(
ARLAGST		VARCHAR(1)  not null,
ARTIKELNR	VARCHAR(30) not null,
ARLAGHYLLA	VARCHAR(10),
ARLAGSALDO	DECIMAL(10,2),
ARINVGRP	VARCHAR(3),
ARABC		VARCHAR(2),
ARVALUTA	VARCHAR(3),
ARIPRIS		DECIMAL(10,2),
ARIKVANT0	DECIMAL(10,2),
ARIKVANT1	DECIMAL(10,2),
ARIKVANT2	DECIMAL(10,2),
ARKALKPRIS	DECIMAL(10,2),
ARBESTKVANT	DECIMAL(10,2),
ARBESTPUNKT	DECIMAL(10,2)
);
use olfixtst;
alter table LAGERSTELLEREG ADD PRIMARY KEY (ARTIKELNR,ARLAGST);
