use olfix;
create table STDLEVPLATS(
STDLEVPLATS VARCHAR(3) not null,
KUNDNR VARCHAR(10) not null,
ADRESS VARCHAR(30) not null,
POSTNR VARCHAR(6) not null,
POSTADR VARCHAR(30) not null,
LAND VARCHAR(30)
);
alter table STDLEVPLATS ADD PRIMARY KEY (STDLEVPLATS,KUNDNR);
use olfixtst;
create table STDLEVPLATS(
STDLEVPLATS VARCHAR(3) not null,
KUNDNR VARCHAR(10) not null,
ADRESS VARCHAR(30) not null,
POSTNR VARCHAR(6) not null,
POSTADR VARCHAR(30) not null,
LAND VARCHAR(30)
);
alter table STDLEVPLATS ADD PRIMARY KEY (STDLEVPLATS,KUNDNR);

