use olfix;
create table ARTIKELREG(
ARTIKELNR	VARCHAR(30) not null,
ARBENEMNING1	VARCHAR(30) not null,
ARBENEMNING2	VARCHAR(30),
ARENHET		VARCHAR(5),
AROMRFAKTOR	INT not null DEFAULT '1',
ARFPRIS		DECIMAL(10,2),
ARLEDTID	VARCHAR(3),
ARPRODKLASS	VARCHAR(5),
ARPRODKTO	VARCHAR(5),
ARLEVNR1	VARCHAR(10),
ARLEVNR2	VARCHAR(10),
ARLEVNR3	VARCHAR(10),
ARNETTOVIKT	DECIMAL(10,2),
ARARTTYP	ENUM ('0','1','2','3')DEFAULT '0',
ARSTRUKT	ENUM (' ','B','I','T','F')DEFAULT ' ',
ARURBENEMNING	VARCHAR(30),
ARURLAND	VARCHAR(30),
ARURARTNR	VARCHAR(30),
ARTULLTAX	VARCHAR(10),
ARVOLYM		DECIMAL(2,3)
);
use olfix;
alter table ARTIKELREG ADD PRIMARY KEY (ARTIKELNR);
use olfixtst;
create table ARTIKELREG(
ARTIKELNR	VARCHAR(30) not null,
ARBENEMNING1	VARCHAR(30) not null,
ARBENEMNING2	VARCHAR(30),
ARENHET		VARCHAR(5),
AROMRFAKTOR	INT not null DEFAULT '1',
ARFPRIS		DECIMAL(10,2),
ARLEDTID	VARCHAR(3),
ARPRODKLASS	VARCHAR(5),
ARPRODKTO	VARCHAR(5),
ARLEVNR1	VARCHAR(10),
ARLEVNR2	VARCHAR(10),
ARLEVNR3	VARCHAR(10),
ARNETTOVIKT	DECIMAL(10,2),
ARARTTYP	ENUM ('0','1','2','3')DEFAULT '0',
ARSTRUKT	ENUM (' ','B','I','T','F')DEFAULT ' ',
ARURBENEMNING	VARCHAR(30),
ARURLAND	VARCHAR(30),
ARURARTNR	VARCHAR(30),
ARTULLTAX	VARCHAR(7),
ARVOLYM		DECIMAL(2,3)
);
use olfixtst;
alter table ARTIKELREG ADD PRIMARY KEY (ARTIKELNR);
