use olfix;
create table ORDERRADREG(
ORDERNR VARCHAR(10) not null,
ORDERRAD INT(4)not null,
KUNDNR VARCHAR(10) not null,
RADORDERTYP ENUM('N','D')DEFAULT 'N',
ARTIKELNR VARCHAR(30) not null,
BESTELLT DECIMAL(10,2) not null,
LEVERERAT DECIMAL(10,2),
RESTNOTERAT DECIMAL(10,2),
APRIS DECIMAL(10,2),
RADRABATT DECIMAL(2,1),
KALKYLPRIS DECIMAL(10,2),
SKATTEKOD VARCHAR(5) not null,
LEVDATUM DATE,
ENHET VARCHAR(4)DEFAULT 'ST'
);
alter table ORDERRADREG ADD PRIMARY KEY (ORDERNR,ORDERRAD);
use olfixtst;
create table ORDERRADREG(
ORDERNR VARCHAR(10) not null,
ORDERRAD INT(4)not null,
KUNDNR VARCHAR(10) not null,
RADORDERTYP ENUM('N','D')DEFAULT 'N',
ARTIKELNR VARCHAR(30) not null,
BESTELLT DECIMAL(10,2) not null,
LEVERERAT DECIMAL(10,2),
RESTNOTERAT DECIMAL(10,2),
APRIS DECIMAL(10,2),
RADRABATT DECIMAL(2,1),
KALKYLPRIS DECIMAL(10,2),
SKATTEKOD VARCHAR(5) not null,
LEVDATUM DATE,
ENHET VARCHAR(4)DEFAULT 'ST'
);
alter table ORDERRADREG ADD PRIMARY KEY (ORDERNR,ORDERRAD);
