use olfix;
create table KURESK (
ORDERNR VARCHAR(10) not null,
FAKTURANR VARCHAR(20) not null,
KUNDNR VARCHAR(10) not null,
FAKTURADATUM DATE,
EXPIREDATUM DATE,
NETTOBELOPP DECIMAL(10,2),
MOMSBELOPP DECIMAL(10,2),
FAKTURABELOPP DECIMAL(10,2),
BETALD enum('J','N') DEFAULT 'N' not null,
BETALDATUM date,
USERID VARCHAR(8),
VALUTA char(3) DEFAULT 'SEK',
VALUTAKURS DECIMAL(10,2) DEFAULT '1' not null,
VALUTABELOPP DECIMAL(10,2) DEFAULT '0,00',
BAR VARCHAR(2),
VERNR INT,
MOMSKTONR VARCHAR(4),
KTONR VARCHAR(4),
DEBETBELOPP DECIMAL(10,2),
BETALTBELOPP DECIMAL(10,2)
);
alter table KURESK ADD PRIMARY KEY (ORDERNR,FAKTURANR);

use olfixtst;
create table KURESK (
ORDERNR VARCHAR(10) not null,
FAKTURANR VARCHAR(20) not null,
KUNDNR VARCHAR(10) not null,
FAKTURADATUM DATE,
EXPIREDATUM DATE,
NETTOBELOPP DECIMAL(10,2),
MOMSBELOPP DECIMAL(10,2),
FAKTURABELOPP DECIMAL(10,2),
BETALD enum('J','N') DEFAULT 'N' not null,
BETALDATUM date,
USERID VARCHAR(8),
VALUTA char(3) DEFAULT 'SEK',
VALUTAKURS DECIMAL(10,2) DEFAULT '1' not null,
VALUTABELOPP DECIMAL(10,2) DEFAULT '0,00',
BAR VARCHAR(2),
VERNR INT,
MOMSKTONR VARCHAR(4),
KTONR VARCHAR(4),
DEBETBELOPP DECIMAL(10,2),
BETALTBELOPP DECIMAL(10,2)
);
alter table KURESK ADD PRIMARY KEY (ORDERNR,FAKTURANR);

