use olfix;
create table VERRAD(VERNR INT not null ,RADNR SMALLINT not null,ARID VARCHAR(2) not null ,KTONR VARCHAR(4),BELOPP DECIMAL(10,2),DK ENUM('D','K'),KSTALLE VARCHAR(4),PROJEKT VARCHAR(4),SUBKTO VARCHAR(4),DEFINITIV ENUM('J','N')DEFAULT 'N',STRUKEN ENUM('J','N')DEFAULT 'N');
alter table VERRAD ADD PRIMARY KEY (VERNR,RADNR,ARID);




