use olfix;
create table ORDERREG(
ORDERNR VARCHAR(10) not null,
KUNDNR VARCHAR(10) not null,
ORDERTYP ENUM('N','D','E','F')DEFAULT 'N',
ORDERSTATUS ENUM('A','N','F','B')DEFAULT 'A',
ORDERDATUM DATE,
LEVDATUM DATE,
LEVADRESS VARCHAR(3)DEFAULT '001',
VARREF VARCHAR(20),
ERREF VARCHAR(20),
SELJARE VARCHAR(20),
GODSMERKE VARCHAR(100),
BETVILLKTYP ENUM('F','P','K') not null,
BETVILLKOR VARCHAR(3) DEFAULT '001',
LEVVILLKOR VARCHAR(3) DEFAULT '001',
LEVSETT VARCHAR(3) DEFAULT '001',
PLOCKLISTA ENUM('J','N') DEFAULT 'J',
FOLJESEDEL ENUM('J','N') DEFAULT 'J',
FRAKTAVG ENUM('J','N') DEFAULT 'J',
SKATTEKOD VARCHAR(3) DEFAULT '001' not null,
VALUTA VARCHAR(3) DEFAULT 'SEK',
EXPORTKOD VARCHAR(3) DEFAULT '001',
SPRAKKOD VARCHAR(3)DEFAULT 'sv'
);
alter table ORDERREG ADD PRIMARY KEY (ORDERNR);
use olfixtst;
create table ORDERREG(
ORDERNR VARCHAR(10) not null,
KUNDNR VARCHAR(10) not null,
ORDERTYP ENUM('N','D','E','F')DEFAULT 'N',
ORDERSTATUS ENUM('A','N','F','B')DEFAULT 'A',
ORDERDATUM DATE,
LEVDATUM DATE,
LEVADRESS VARCHAR(3)DEFAULT '001',
VARREF VARCHAR(20),
ERREF VARCHAR(20),
SELJARE VARCHAR(20),
GODSMERKE VARCHAR(100),
BETVILLKTYP ENUM('F','P','K') not null,
BETVILLKOR VARCHAR(3) DEFAULT '001',
LEVVILLKOR VARCHAR(3) DEFAULT '001',
LEVSETT VARCHAR(3) DEFAULT '001',
PLOCKLISTA ENUM('J','N') DEFAULT 'J',
FOLJESEDEL ENUM('J','N') DEFAULT 'J',
FRAKTAVG ENUM('J','N') DEFAULT 'J',
SKATTEKOD VARCHAR(3) DEFAULT '001' not null,
VALUTA VARCHAR(3) DEFAULT 'SEK',
EXPORTKOD VARCHAR(3) DEFAULT '001',
SPRAKKOD VARCHAR(3)DEFAULT 'sv'
);
alter table ORDERREG ADD PRIMARY KEY (ORDERNR);
