use olfix;
DROP TABLE IF EXISTS PLOCKLISTEREG;
create table PLOCKLISTEREG(
PLOCKNR INT not null auto_increment PRIMARY KEY,
ORDERNR VARCHAR(10) not null,
ORDERRAD INT(4)not null,
KUNDNR VARCHAR(10) not null,
ARTIKELNR VARCHAR(30) not null,
BENEMNING VARCHAR(60),
LEVERANSVECKA VARCHAR(5),
BESTELLT DECIMAL(10,2) not null,
ATTLEVERERA DECIMAL(10,2) not null,
LEVERERAT DECIMAL(10,2) not null,
PLOCKAT DECIMAL(10,2) not null
RESTNOTERAT DECIMAL(10,2) not null,
LEVDATUM DATE,
ENHET VARCHAR(4),
PLOCKSTATUS ENUM ('P','U','B') DEFAULT 'P',
PLOCKDATUM DATE not null
);


use olfixtst;
DROP TABLE IF EXISTS PLOCKLISTEREG;
create table PLOCKLISTEREG(
PLOCKNR INT not null auto_increment PRIMARY KEY,
ORDERNR VARCHAR(10) not null,
ORDERRAD INT(4)not null,
KUNDNR VARCHAR(10) not null,
ARTIKELNR VARCHAR(30) not null,
BENEMNING VARCHAR(60),
LEVERANSVECKA VARCHAR(5),
BESTELLT DECIMAL(10,2) not null,
ATTLEVERERA DECIMAL(10,2) not null,
LEVERERAT DECIMAL(10,2) not null,
PLOCKAT DECIMAL(10,2) not null
RESTNOTERAT DECIMAL(10,2) not null,
LEVDATUM DATE,
ENHET VARCHAR(4),
PLOCKSTATUS ENUM ('P','B') DEFAULT 'P',
PLOCKDATUM DATE not null
);
