# Connection: olfix
# Host: localhost
# Saved: 2003-08-18 07:59:11
# 
SELECT EXPIREDATUM,LEVNR,FAKTURANR,FAKTBELOPP,VALUTA
FROM `LEVRESK`
where EXPIREDATUM < " 2003-09-09" and BETALD = "N"
order by LEVNR,EXPIREDATUM,FAKTURANR;