use olfixtst;
UPDATE FTGDATA SET FDATA = "PROGRAM AB" WHERE POSTTYP = "FNAMN";
UPDATE FTGDATA SET FDATA = "991199-1991" WHERE POSTTYP = "FTGNR";
UPDATE FTGDATA SET FDATA = "Box 69" WHERE POSTTYP = "ADR1";
UPDATE FTGDATA SET FDATA = "199 98" WHERE POSTTYP = "ADR2";
UPDATE FTGDATA SET FDATA = "PROGSTAD" WHERE POSTTYP = "ADR3";
UPDATE FTGDATA SET FDATA = "Syntaxvägen 99" WHERE POSTTYP = "ADR4";
UPDATE FTGDATA SET FDATA = "199 98" WHERE POSTTYP = "ADR5";
UPDATE FTGDATA SET FDATA = "PROGSTAD" WHERE POSTTYP = "ADR6";
UPDATE FTGDATA SET FDATA = "Verktygsgatan 11" WHERE POSTTYP = "ADR7";
UPDATE FTGDATA SET FDATA = "199 97" WHERE POSTTYP = "ADR8";
UPDATE FTGDATA SET FDATA = "PROGSTAD" WHERE POSTTYP = "ADR9";
UPDATE FTGDATA SET FDATA = "09-199300" WHERE POSTTYP = "TFN1";
UPDATE FTGDATA SET FDATA = "070-98765411" WHERE POSTTYP = "TFN2";
UPDATE FTGDATA SET FDATA = "09-199300" WHERE POSTTYP = "TFNVX";
UPDATE FTGDATA SET FDATA = "070-98765411" WHERE POSTTYP = "TFNMB";
UPDATE FTGDATA SET FDATA = "09-199397" WHERE POSTTYP = "TFAX";
UPDATE FTGDATA SET FDATA = "jan@pihlgren.se" WHERE POSTTYP = "EML1";
UPDATE FTGDATA SET FDATA = "0" WHERE POSTTYP = "KORNR";
UPDATE FTGDATA SET FDATA = "25" WHERE POSTTYP = "MOMS1";
UPDATE FTGDATA SET FDATA = "12" WHERE POSTTYP = "MOMS2";
UPDATE FTGDATA SET FDATA = "6" WHERE POSTTYP = "MOMS3";
UPDATE FTGDATA SET FDATA = " " WHERE POSTTYP = "MOMS4";
UPDATE FTGDATA SET FDATA = " " WHERE POSTTYP = "MOMS5";
UPDATE FTGDATA SET FDATA = "0" WHERE POSTTYP = "KORNR";
UPDATE FTGDATA SET FDATA = "N" WHERE POSTTYP = "AUTOK";
UPDATE FTGDATA SET FDATA = "2641" WHERE POSTTYP = "MOMSI";
UPDATE FTGDATA SET FDATA = "2611" WHERE POSTTYP = "MOMSU";






