######################################################################
# Automatically generated by qmake (1.03a) Mon Jan 20 07:17:36 2003
######################################################################

TEMPLATE = app

# Input
HEADERS += frmdspusr.ui.h
INTERFACES += frmdspusr.ui
SOURCES += main.cpp
