######################################################################
# Automatically generated by qmake (1.04a) Sat Nov 13 17:09:36 2004
######################################################################

TARGET=DSPUSRW
DESTDIR+=/home/jan/Utveckling/OLFIX/bin
TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += frmdspusr.ui.h
INTERFACES += frmdspusr.ui
SOURCES += main.cpp
