######################################################################
# Automatically generated by qmake (1.04a) Sun Jun 29 08:01:31 2003
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += levresk.ui.h
INTERFACES += levresk.ui
SOURCES += main.cpp
