######################################################################
# Automatically generated by qmake (1.04a) Sun Nov 14 05:38:34 2004
######################################################################

TARGET=LEVRESKW
DESTDIR+=/opt/olfix/bin
TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += levresk.ui.h
INTERFACES += levresk.ui
SOURCES += main.cpp
