######################################################################
# Automatically generated by qmake (1.04a) Fri Nov 12 15:44:26 2004
######################################################################

TARGET=ADDORDW
DESTDIR+=/opt/olfix/bin
TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += frmaddorder.ui.h
INTERFACES += frmaddorder.ui
SOURCES += main.cpp
