######################################################################
# Automatically generated by qmake (1.04a) Sun Oct 12 07:58:24 2003
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += frmaddorder.ui.h
INTERFACES += frmaddorder.ui
SOURCES += main.cpp
TARGET = $(OLFIXBIN)/ADDORDW