######################################################################
# Automatically generated by qmake (1.03a) Fri Feb 21 07:54:10 2003
######################################################################

TEMPLATE = app

# Input
HEADERS += frmdspvaluta.ui.h
INTERFACES += frmdspvaluta.ui
SOURCES += main.cpp
