######################################################################
# Automatically generated by qmake (1.04a) Sat Nov 13 17:13:00 2004
######################################################################

TARGET=DSPVALW
DESTDIR+=/home/jan/Utveckling/OLFIX/bin
TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += frmdspvaluta.ui.h
INTERFACES += frmdspvaluta.ui
SOURCES += main.cpp
