######################################################################
# Automatically generated by qmake (1.07a) Sun Nov 19 06:50:50 2006
######################################################################

TARGET=DELOFFW
DESTDIR+=/home/jan/Development/OLFIX/bin
TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += frmdeloffert.ui.h
INTERFACES += frmdeloffert.ui
SOURCES += main.cpp
