######################################################################
# Automatically generated by qmake (1.03a) Fri Feb 21 05:21:00 2003
######################################################################

TEMPLATE = app

# Input
HEADERS += frmaddvaluta.ui.h
INTERFACES += frmaddvaluta.ui
SOURCES += main.cpp
