######################################################################
# Automatically generated by qmake (1.04a) Fri Nov 12 17:19:41 2004
######################################################################

TARGET=ADDVALW
DESTDIR+=/opt/olfix/bin
TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += frmaddvaluta.ui.h
INTERFACES += frmaddvaluta.ui
SOURCES += main.cpp
