######################################################################
# Automatically generated by qmake (1.04a) Sun Nov 16 16:29:36 2003
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += frmchgartikel.ui.h
INTERFACES += frmchgartikel.ui
SOURCES += main.cpp
