######################################################################
# Automatically generated by qmake (1.04a) Sat Nov 13 06:14:12 2004
######################################################################

TARGET=CHGARW
DESTDIR+=/home/jan/Utveckling/OLFIX/bin
TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += frmchgartikel.ui.h
INTERFACES += frmchgartikel.ui
SOURCES += main.cpp
