######################################################################
# Automatically generated by qmake (1.04a) Tue Mar 30 05:29:48 2004
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += frmhuvudbok.ui.h
INTERFACES += frmhuvudbok.ui
SOURCES += main.cpp
