######################################################################
# Automatically generated by qmake (1.04a) Sun Nov 14 05:20:49 2004
######################################################################

TARGET=HUVBOKW
DESTDIR+=/home/jan/Utveckling/OLFIX/bin
TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += frmhuvudbok.ui.h
INTERFACES += frmhuvudbok.ui
SOURCES += main.cpp
