######################################################################
# Automatically generated by qmake (1.03a) Mon Dec 30 07:04:00 2002
######################################################################

TEMPLATE = app
CONFIG -= moc

# Input
HEADERS += getuser.h
INTERFACES += frmlistrights.ui
SOURCES += main.cpp
