######################################################################
# Automatically generated by qmake (1.04a) Mon Nov 15 05:20:29 2004
######################################################################

TARGET=LSTRGTW
DESTDIR+=/opt/olfix/bin
TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += getuser.h
INTERFACES += frmlistrights.ui
SOURCES += main.cpp
