######################################################################
# Automatically generated by qmake (1.04a) Fri Nov 12 20:24:58 2004
######################################################################

TARGET=SRCHKUW
DESTDIR+=/home/jan/Utveckling/OLFIX/bin
TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += frmhittakund.ui.h
INTERFACES += frmhittakund.ui
SOURCES += main.cpp
