######################################################################
# Automatically generated by qmake (1.04a) Mon Mars 31 05:40:13 2005
######################################################################

TARGET=PLORDW
DESTDIR+=/opt/olfix/bin
TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += prtplkuord.ui.h
INTERFACES += prtplkuord.ui
SOURCES += main.cpp
