######################################################################
# Automatically generated by qmake (1.04a) Tue Nov 15 06:31:13 2005
######################################################################

TARGET=KURESKW
DESTDIR+=/opt/olfix/bin
TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += frmkundreskontra.ui.h
INTERFACES += frmkundreskontra.ui
SOURCES += main.cpp
