######################################################################
# Automatically generated by qmake (1.04a) Thu Nov 24 08:39:44 2005
######################################################################

TARGET=DSPTXTW
DESTDIR+=/home/jan/Utveckling/OLFIX/bin
TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += frmdsptext.ui.h
INTERFACES += frmdsptext.ui
SOURCES += main.cpp
