######################################################################
# Automatically generated by qmake (1.04a) Thu Dec 11 09:01:06 2003
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += frmaddtxt.ui.h
INTERFACES += frmaddtxt.ui
SOURCES += main.cpp
