######################################################################
# Automatically generated by qmake (1.04a) Fri Nov 12 17:12:08 2004
######################################################################

TARGET=ADDTXTW
DESTDIR+=/opt/olfix/bin
TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += frmaddtxt.ui.h
INTERFACES += frmaddtxt.ui
SOURCES += main.cpp
