######################################################################
# Automatically generated by qmake (1.04a) Tue Nov 1 08:12:51 2005
######################################################################

TARGET=KUFAKTW
DESTDIR+=/home/jan/Utveckling/OLFIX/bin
TEMPLATE = app

# Input
HEADERS += kundfaktura.ui.h
INTERFACES += kundfaktura.ui
SOURCES += main.cpp
