######################################################################
# Automatically generated by qmake (1.04a) Sun Dec 21 05:15:56 2003
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += frmdspbest.ui.h
INTERFACES += frmdspbest.ui
SOURCES += main.cpp
