######################################################################
# Automatically generated by qmake (1.04a) Sat Nov 13 15:04:10 2004
######################################################################

TARGET=DSPINKW
DESTDIR+=/opt/olfix/bin
TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += frmdspbest.ui.h
INTERFACES += frmdspbest.ui
SOURCES += main.cpp
