######################################################################
# Automatically generated by qmake (1.04a) Wed Dec 1 05:44:47 2004
######################################################################

TARGET=LSTPKDW
DESTDIR+=/opt/olfix/bin
TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += frmlistprodkod.ui.h
INTERFACES += frmlistprodkod.ui
SOURCES += main.cpp
