######################################################################
# Automatically generated by qmake (1.04a) Tus Mars 1 16:08:32 2005
######################################################################

TARGET=LSTBARW
DESTDIR+=/home/jan/Development/OLFIX/bin
TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += frmlistbar.ui.h
INTERFACES += frmlistbar.ui
SOURCES += main.cpp
