######################################################################
# Automatically generated by qmake (1.04a) Wed Mar 16 07:29:58 2005
######################################################################

TARGET=LSTORDW
DESTDIR+=/home/jan/Utveckling/OLFIX/bin
TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += frmlistkundorder.ui.h
INTERFACES += frmlistkundorder.ui
SOURCES += main.cpp
