######################################################################
# Automatically generated by qmake (1.03a) Thu Apr 17 05:13:45 2003
######################################################################

TEMPLATE = app
CONFIG -= moc

# Input
INTERFACES += frmchgftgdata.ui
SOURCES += main.cpp
