######################################################################
# Automatically generated by qmake (1.04a) Sat Nov 26 10:46:54 2005
######################################################################

TARGET=CHGFTGW
DESTDIR+=/opt/olfix/bin
TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += frmchgftgdata.ui.h
INTERFACES += frmchgftgdata.ui
SOURCES += main.cpp
