######################################################################
# Automatically generated by qmake (1.04a) Sat Nov 13 06:31:31 2004
######################################################################

TARGET=CHGFTGW
DESTDIR+=/home/jan/Utveckling/OLFIX/bin
TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += frmchgftgdata.ui.h
INTERFACES += frmchgftgdata.ui
SOURCES += main.cpp
