######################################################################
# Automatically generated by qmake (1.03a) Thu Feb 27 10:52:14 2003
######################################################################

TEMPLATE = app

# Input
HEADERS += Bokfstd.ui.h
INTERFACES += Bokfstd.ui
SOURCES += main.cpp
