######################################################################
# Automatically generated by qmake (1.04a) Fri Nov 12 20:28:24 2004
######################################################################

TARGET=BOKFORSW
DESTDIR+=/home/jan/Utveckling/OLFIX/bin
TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += Bokfstd.ui.h
INTERFACES += Bokfstd.ui
SOURCES += main.cpp
