######################################################################
# Automatically generated by qmake (1.04a) Fri Aug 15 07:53:06 2003
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += frmaddftgdata.ui.h
INTERFACES += frmaddftgdata.ui
SOURCES += main.cpp
