######################################################################
# Automatically generated by qmake (1.04a) Thu Nov 11 06:31:28 2004
######################################################################

TARGET=ADDFTGW
DESTDIR+=/home/jan/Utveckling/OLFIX/bin
TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += frmaddftgdata.ui.h
INTERFACES += frmaddftgdata.ui
SOURCES += main.cpp
