######################################################################
# Automatically generated by qmake (1.04a) Sat Nov 13 06:18:10 2004
######################################################################

TARGET=CHGBARW
DESTDIR+=/opt/olfix/bin
TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += frmchgbar.ui.h
INTERFACES += frmchgbar.ui
SOURCES += main.cpp
