######################################################################
# Automatically generated by qmake (1.03a) Wed Apr 2 08:55:16 2003
######################################################################

TEMPLATE = app

# Input
HEADERS += frmchgbar.ui.h
INTERFACES += frmchgbar.ui
SOURCES += main.cpp
