######################################################################
# Automatically generated by qmake (1.04a) Sat Nov 13 11:37:08 2004
######################################################################

TARGET=DELVALW
DESTDIR+=/home/jan/Utveckling/OLFIX/bin
TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += frmdelvaluta.ui.h
INTERFACES += frmdelvaluta.ui
SOURCES += main.cpp
