######################################################################
# Automatically generated by qmake (1.03a) Fri Feb 21 13:15:09 2003
######################################################################

TEMPLATE = app

# Input
HEADERS += frmdelvaluta.ui.h
INTERFACES += frmdelvaluta.ui
SOURCES += main.cpp
