#!/bin/sh
QTDIR=/usr/lib/qt3
export QTDIR
OLFIXBIN=/usr/local/olfix/bin
export OLFIXBIN
OLFIXSRC=/usr/local/olfix/src
export OLFIXSRC
OLFIXINSTALL=$HOME/tmp
export OLFIXINSTALL
OLFIXDEST=/usr/local/olfix
export OLFIXDEST

QPATH=/usr/lib/qt3/bin
PATH=$PATH:$QPATH
export PATH

mkdir /usr/local/olfix
mkdir /usr/local/olfix/bin
mkdir /usr/local/olfix/data
mkdir /usr/local/olfix/doc
mkdir /usr/local/olfix/doc/Image
mkdir /usr/local/olfix/include
mkdir /usr/local/olfix/lib
mkdir /usr/local/olfix/sql
mkdir /usr/local/olfix/src
mkdir /usr/local/olfix/util
mkdir /usr/local/olfix/src/AddBar
mkdir /usr/local/olfix/src/AddKonto
mkdir /usr/local/olfix/src/AddKstalle
mkdir /usr/local/olfix/src/AddProg
mkdir /usr/local/olfix/src/AddRights
mkdir /usr/local/olfix/src/AddUser
mkdir /usr/local/olfix/src/AddValuta
mkdir /usr/local/olfix/src/ADMIN
mkdir /usr/local/olfix/src/BokforStd
mkdir /usr/local/olfix/src/ChangeKonto
mkdir /usr/local/olfix/src/ChangeUser
mkdir /usr/local/olfix/src/ChangeValuta
mkdir /usr/local/olfix/src/DelRights
mkdir /usr/local/olfix/src/DelUser
mkdir /usr/local/olfix/src/DelValuta
mkdir /usr/local/olfix/src/DspKstalle
mkdir /usr/local/olfix/src/DspUser
mkdir /usr/local/olfix/src/DspValuta
mkdir /usr/local/olfix/src/Kontorapport
mkdir /usr/local/olfix/src/ListFunc
mkdir /usr/local/olfix/src/ListKonto
mkdir /usr/local/olfix/src/ListKst
mkdir /usr/local/olfix/src/ListRights
mkdir /usr/local/olfix/src/ListUser
mkdir /usr/local/olfix/src/ListValuta
mkdir /usr/local/olfix/src/MenyOlfixW
cp $OLFIXINSTALL/bin/* $OLFIXDEST/bin
cp $OLFIXINSTALL/data/* $OLFIXDEST/data
cp $OLFIXINSTALL/doc/* $OLFIXDEST/doc
cp $OLFIXINSTALL/doc/Image/* $OLFIXDEST/doc/Image
cp $OLFIXINSTALL/include/* $OLFIXDEST/include
cp $OLFIXINSTALL/lib/* $OLFIXDEST/lib
cp $OLFIXINSTALL/sql/* $OLFIXDEST/sql
cp $OLFIXINSTALL/util/* $OLFIXDEST/util
cp $OLFIXINSTALL/src/*.c $OLFIXDEST/src
cp $OLFIXINSTALL/src/*.h $OLFIXDEST/src
cp $OLFIXINSTALL/src/Makefile_ALL.txt $OLFIXDEST/src/Makefile
cp $OLFIXINSTALL/src/AddBar/* $OLFIXDEST/src/AddBar
cp $OLFIXINSTALL/src/AddKonto/* $OLFIXDEST/src/AddKonto
cp $OLFIXINSTALL/src/AddKstall/* $OLFIXDEST/src/AddKstalle
cp $OLFIXINSTALL/src/AddProg/* $OLFIXDEST/src/AddProg
cp $OLFIXINSTALL/src/AddRights/* $OLFIXDEST/src/AddRights
cp $OLFIXINSTALL/src/AddUser/* $OLFIXDEST/src/AddUser
cp $OLFIXINSTALL/src/AddValuta/* $OLFIXDEST/src/AddValuta
cp $OLFIXINSTALL/src/ADMIN/* $OLFIXDEST/src/ADMIN
cp $OLFIXINSTALL/src/BokforStd/* $OLFIXDEST/src/BokforStd
cp $OLFIXINSTALL/src/ChangeKonto/* $OLFIXDEST/src/ChangeKonto
cp $OLFIXINSTALL/src/ChangeUser/* $OLFIXDEST/src/ChangeUser
cp $OLFIXINSTALL/src/ChangeValuta/* $OLFIXDEST/src/ChangeValuta
cp $OLFIXINSTALL/src/DelRights/* $OLFIXDEST/src/DelRights
cp $OLFIXINSTALL/src/DelUser/* $OLFIXDEST/src/DelUser
cp $OLFIXINSTALL/src/DelValuta/* $OLFIXDEST/src/DelValuta
cp $OLFIXINSTALL/src/DspKstalle/* $OLFIXDEST/src/DspKstalle
cp $OLFIXINSTALL/src/DspUser/* $OLFIXDEST/src/DspUser
cp $OLFIXINSTALL/src/DspValuta/* $OLFIXDEST/src/DspValuta
cp $OLFIXINSTALL/src/Kontorapport/* $OLFIXDEST/src/Kontorapport
cp $OLFIXINSTALL/src/ListFunc/* $OLFIXDEST/src/ListFunc
cp $OLFIXINSTALL/src/ListKst/* $OLFIXDEST/src/ListKst
cp $OLFIXINSTALL/src/ListKonto/* $OLFIXDEST/src/ListKonto
cp $OLFIXINSTALL/src/ListRights/* $OLFIXDEST/src/ListRights
cp $OLFIXINSTALL/src/ListUser/* $OLFIXDEST/src/ListUser
cp $OLFIXINSTALL/src/ListValuta/* $OLFIXDEST/src/ListValuta
cp $OLFIXINSTALL/src/MenyOlfixW/* $OLFIXDEST/src/MenyOlfixW

cd $OLFIXBIN
chown olfix *
chgrp olfix *
chmod 0010 *
chmod 2111 OLFIXW
echo ""
echo "***************************************************"
echo "Kopiera filen $OLFIXDEST/util/.olfixrc till ditt home-bibliotek"
echo ""
echo "Den ser ut så här nu: PATH=/usr/local/olfix/bin"
echo ""
echo "Editera filen .olfixrc så den passar dig."
echo "***************************************************"
echo ""
