#!/bin/sh
OLFIXINSTALL=$HOME/tmp
export OLFIXINSTALL

OLFIXDEST=/usr/local/olfix/
export OLFIXDEST

OLFIXBIN=$OLFIXDEST/bin
export OLFIXBIN

OLFIXSRC=$OLFIXDEST/src
export OLFIXSRC


cp $OLFIXINSTALL/data/* $OLFIXDEST/data
cp $OLFIXINSTALL/doc/* $OLFIXDEST/doc
cp $OLFIXINSTALL/doc/Image/* $OLFIXDEST/doc/Image
cp $OLFIXINSTALL/include/* $OLFIXDEST/include
cp $OLFIXINSTALL/lib/* $OLFIXDEST/lib
cp $OLFIXINSTALL/sql/* $OLFIXDEST/sql
cp $OLFIXINSTALL/src/*.c $OLFIXDEST/src
cp $OLFIXINSTALL/src/*.h $OLFIXDEST/src
cp $OLFIXINSTALL/src/Makefile_ALL.txt $OLFIXDEST/src/Makefile
cp $OLFIXINSTALL/src/AddBar/* $OLFIXDEST/src/AddBar
cp $OLFIXINSTALL/src/AddKonto/* $OLFIXDEST/src/AddKonto
cp $OLFIXINSTALL/src/AddKstall/* $OLFIXDEST/src/AddKstalle
cp $OLFIXINSTALL/src/AddProg/* $OLFIXDEST/src/AddProg
cp $OLFIXINSTALL/src/AddRights/* $OLFIXDEST/src/AddRights
cp $OLFIXINSTALL/src/AddUser/* $OLFIXDEST/src/AddUser
cp $OLFIXINSTALL/src/AddValuta/* $OLFIXDEST/src/AddValuta
cp $OLFIXINSTALL/src/ADMIN/* $OLFIXDEST/src/ADMIN
cp $OLFIXINSTALL/src/BokforStd/* $OLFIXDEST/src/BokforStd
cp $OLFIXINSTALL/src/ChangeKonto/* $OLFIXDEST/src/ChangeKonto
cp $OLFIXINSTALL/src/ChangeUser/* $OLFIXDEST/src/ChangeUser
cp $OLFIXINSTALL/src/ChangeValuta/* $OLFIXDEST/src/ChangeValuta
cp $OLFIXINSTALL/src/DelRights/* $OLFIXDEST/src/DelRights
cp $OLFIXINSTALL/src/DelUser/* $OLFIXDEST/src/DelUser
cp $OLFIXINSTALL/src/DelValuta/* $OLFIXDEST/src/DelValuta
cp $OLFIXINSTALL/src/DspKstalle/* $OLFIXDEST/src/DspKstalle
cp $OLFIXINSTALL/src/DspUser/* $OLFIXDEST/src/DspUser
cp $OLFIXINSTALL/src/DspValuta/* $OLFIXDEST/src/DspValuta
cp $OLFIXINSTALL/src/Kontorapport/* $OLFIXDEST/src/Kontorapport
cp $OLFIXINSTALL/src/ListFunc/* $OLFIXDEST/src/ListFunc
cp $OLFIXINSTALL/src/ListKst/* $OLFIXDEST/src/ListKst
cp $OLFIXINSTALL/src/ListKonto/* $OLFIXDEST/src/ListKonto
cp $OLFIXINSTALL/src/ListRights/* $OLFIXDEST/src/ListRights
cp $OLFIXINSTALL/src/ListUser/* $OLFIXDEST/src/ListUser
cp $OLFIXINSTALL/src/ListValuta/* $OLFIXDEST/src/ListValuta
cp $OLFIXINSTALL/src/MenyOlfixW/* $OLFIXDEST/src/MenyOlfixW

