######################################################################
# Automatically generated by qmake (1.04a) Mon Nov 15 05:31:44 2004
######################################################################

TARGET=LSTVALW
DESTDIR+=/opt/olfix/bin
TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += frmlistvaluta.ui.h
INTERFACES += frmlistvaluta.ui
SOURCES += main.cpp
