######################################################################
# Automatically generated by qmake (1.03a) Thu Feb 20 15:47:59 2003
######################################################################

TEMPLATE = app

# Input
HEADERS += frmlistvaluta.ui.h
INTERFACES += frmlistvaluta.ui
SOURCES += main.cpp
