######################################################################
# Automatically generated by qmake (1.04a) Thu Nov 11 06:26:03 2004
######################################################################

TARGET=ADDBETVW
DESTDIR+=/opt/olfix/bin
TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += frmaddbetalvillkor.ui.h
INTERFACES += frmaddbetalvillkor.ui
SOURCES += main.cpp
