######################################################################
# Automatically generated by qmake (1.04a) Sat Nov 22 16:58:30 2003
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += frmaddbetalvillkor.ui.h
INTERFACES += frmaddbetalvillkor.ui
SOURCES += main.cpp
