######################################################################
# Automatically generated by qmake (1.03a) Sat Jan 18 13:02:13 2003
######################################################################

TEMPLATE = app

# Input
HEADERS += frmaddbar.ui.h
INTERFACES += frmaddbar.ui
SOURCES += main.cpp
