######################################################################
# Automatically generated by qmake (1.04a) Thu Nov 11 06:19:51 2004
######################################################################

TARGET=ADDBARW
DESTDIR+=/home/jan/Utveckling/OLFIX/bin
TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += frmaddbar.ui.h
INTERFACES += frmaddbar.ui
SOURCES += main.cpp
