######################################################################
# Automatically generated by qmake (1.04a) Fri Nov 12 05:47:07 2004
######################################################################

TARGET=DELUSRW
DESTDIR+=/home/jan/Utveckling/OLFIX/bin
TEMPLATE = app

# Input
HEADERS += frmdelusr.ui.h
INTERFACES += frmdelusr.ui
SOURCES += main.cpp
