######################################################################
# Automatically generated by qmake (1.04a) Sat Nov 13 11:31:24 2004
######################################################################

TARGET=DELUSRW
DESTDIR+=/opt/olfix/bin
TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += frmdelusr.ui.h
INTERFACES += frmdelusr.ui
SOURCES += main.cpp
