######################################################################
# Automatically generated by qmake (1.03a) Sun Feb 2 05:02:18 2003
######################################################################

TEMPLATE = app

# Input
HEADERS += frmdelusr.ui.h
INTERFACES += frmdelusr.ui
SOURCES += main.cpp
