######################################################################
# Automatically generated by qmake (1.04a) Sun Nov 14 08:11:09 2004
######################################################################

TARGET=LSTFNCW
DESTDIR+=/opt/olfix/bin
TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += frmlistfunk.ui.h
INTERFACES += frmlistfunk.ui
SOURCES += main.cpp
