######################################################################
# Automatically generated by qmake (1.03a) Wed Feb 5 07:44:43 2003
######################################################################

TEMPLATE = app

# Input
HEADERS += frmlistfunk.ui.h
INTERFACES += frmlistfunk.ui
SOURCES += main.cpp
