######################################################################
# Automatically generated by qmake (1.07a) Thu Nov 23 11:25:58 2006
######################################################################

TARGET=OFF2ORDW
DESTDIR+=/home/jan/Development/OLFIX/bin
TEMPLATE = app
CONFIG -= moc
INCLUDEPATH += .

# Input
INTERFACES += offerttillorder.ui
SOURCES += main.cpp
