######################################################################
# Automatically generated by qmake (1.04a) Tor Mars 24 08:44:26 2005
######################################################################

TARGET=DSPORDW
DESTDIR+=/home/jan/Utveckling/OLFIX/bin
TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += frmdsporder.ui.h
INTERFACES += frmdsporder.ui
SOURCES += main.cpp
