######################################################################
# Automatically generated by qmake (1.03a) Sun Dec 29 14:11:55 2002
######################################################################

TEMPLATE = app

# Input
HEADERS += gettime.h getuser.h
INTERFACES += admin.ui
SOURCES += main.cpp
