######################################################################
# Automatically generated by qmake (1.07a) Mon Jul 16 07:48:16 2007
######################################################################

TARGET=CPYKTOW
DESTDIR+=/home/jan/Development/OLFIX/bin
TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += frmcopyktoplan.ui.h
INTERFACES += frmcopyktoplan.ui
SOURCES += main.cpp
