######################################################################
# Automatically generated by qmake (1.04a) Thu Nov 18 08:11:01 2004
######################################################################

TARGET=RPTSIEW
DESTDIR+=/opt/olfix/bin
TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += frmrapportsie.ui.h
INTERFACES += frmrapportsie.ui
SOURCES += main.cpp
