######################################################################
# Automatically generated by qmake (1.04a) Sun Nov 14 06:59:54 2004
######################################################################

TARGET=LSTARW
DESTDIR+=/home/jan/Utveckling/OLFIX/bin
TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += frmlistartikel.ui.h
INTERFACES += frmlistartikel.ui
SOURCES += main.cpp
