######################################################################
# Automatically generated by qmake (1.04a) Sun Nov 23 09:22:04 2003
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += frmlistartikel.ui.h
INTERFACES += frmlistartikel.ui
SOURCES += main.cpp
