######################################################################
# Automatically generated by qmake (1.07a) Thu Apr 27 05:42:32 2006
######################################################################

TARGET=DSPOFFW
DESTDIR+=/home/jan/Development/OLFIX/bin
TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += frmdspoffert.ui.h
INTERFACES += frmdspoffert.ui
SOURCES += main.cpp
