######################################################################
# Automatically generated by qmake (1.07a) Fri Jul 13 08:46:50 2007
######################################################################

TARGET=DELLEVSW
DESTDIR+=/home/jan/Development/OLFIX/bin
TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += frmdellevsett.ui.h
INTERFACES += frmdellevsett.ui
SOURCES += main.cpp
