######################################################################
# Automatically generated by qmake (1.04a) Mon Nov 15 05:13:44 2004
######################################################################

TARGET=LSTLEVSW
DESTDIR+=/home/jan/Utveckling/OLFIX/bin
TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += frmlistlevsett.ui.h
INTERFACES += frmlistlevsett.ui
SOURCES += main.cpp
