######################################################################
# Automatically generated by qmake (1.04a) Mon Feb 9 08:08:38 2004
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += frmlistlevsett.ui.h
INTERFACES += frmlistlevsett.ui
SOURCES += main.cpp
