######################################################################
# Automatically generated by qmake (1.04a) Sat Sep 6 05:11:12 2003
######################################################################

TEMPLATE = app
CONFIG -= moc
INCLUDEPATH += .

# Input
INTERFACES += frmaddkund.ui
SOURCES += main.cpp
