######################################################################
# Automatically generated by qmake (1.04a) Fri Nov 12 13:19:44 2004
######################################################################

TARGET=ADDKUW
DESTDIR+=/opt/olfix/bin
TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += frmaddkund.ui.h
INTERFACES += frmaddkund.ui
SOURCES += main.cpp
