######################################################################
# Automatically generated by qmake (1.04a) Tue Jun 10 11:08:42 2003
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += frmdsplev.ui.h
INTERFACES += frmdsplev.ui
SOURCES += main.cpp
