######################################################################
# Automatically generated by qmake (1.04a) Sat Nov 13 17:06:11 2004
######################################################################

TARGET=DSPLEVW
DESTDIR+=/opt/olfix/bin
TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += frmdsplev.ui.h
INTERFACES += frmdsplev.ui
SOURCES += main.cpp
