######################################################################
# Automatically generated by qmake (1.04a) Mon Nov 8 10:27:01 2004
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += frmlistlevplats.ui.h
INTERFACES += frmlistlevplats.ui
SOURCES += main.cpp
