######################################################################
# Automatically generated by qmake (1.04a) Mon Nov 15 05:10:18 2004
######################################################################

TARGET=LSTLEVPW
DESTDIR+=/home/jan/Utveckling/OLFIX/bin
TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += frmlistlevplats.ui.h
INTERFACES += frmlistlevplats.ui
SOURCES += main.cpp
