######################################################################
# Automatically generated by qmake (1.04a) Tue Jan 11 07:22:07 2005
######################################################################

TARGET=RESRPTW
DESTDIR+=/opt/olfix/bin
TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += frmresultatrapport.ui.h
INTERFACES += frmresultatrapport.ui
SOURCES += main.cpp
