######################################################################
# Automatically generated by qmake (1.04a) Mon Nov 15 05:44:14 2004
######################################################################

TARGET=RPTGENW
DESTDIR+=/home/jan/Utveckling/OLFIX/bin
TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += frmrapportgen.ui.h
INTERFACES += frmrapportgen.ui
SOURCES += main.cpp
