######################################################################
# Automatically generated by qmake (1.04a) Tue Aug 26 06:33:33 2003
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += frmrapportgen.ui.h
INTERFACES += frmrapportgen.ui
SOURCES += main.cpp
