######################################################################
# Automatically generated by qmake (1.04a) Sun Nov 14 08:53:16 2004
######################################################################

TARGET=LSTKSTW
DESTDIR+=/home/jan/Utveckling/OLFIX/bin
TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += frmlistkst.ui.h
INTERFACES += frmlistkst.ui
SOURCES += main.cpp
