######################################################################
# Automatically generated by qmake (1.03a) Sat Feb 22 11:15:45 2003
######################################################################

TEMPLATE = app

# Input
HEADERS += frmlistkst.ui.h
INTERFACES += frmlistkst.ui
SOURCES += main.cpp
