######################################################################
# Automatically generated by qmake (1.04a) Mon Nov 15 05:06:38 2004
######################################################################

TARGET=LSTLEVW
DESTDIR+=/opt/olfix/bin
TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += frmlistlev.ui.h
INTERFACES += frmlistlev.ui
SOURCES += main.cpp
