######################################################################
# Automatically generated by qmake (1.04a) Sun Dec 7 05:59:53 2003
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += frmlistlev.ui.h
INTERFACES += frmlistlev.ui
SOURCES += main.cpp
