######################################################################
# Automatically generated by qmake (1.04a) Fri Nov 12 17:06:44 2004
######################################################################

TARGET=ADDLEVPW
DESTDIR+=/opt/olfix/bin
TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += frmaddlevplats.ui.h
INTERFACES += frmaddlevplats.ui
SOURCES += main.cpp
