######################################################################
# Automatically generated by qmake (1.04a) Fri Nov 12 17:06:44 2004
######################################################################

TARGET=ADDLEVPW
DESTDIR+=/home/jan/Utveckling/OLFIX/bin
TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += frmaddlevplats.ui.h
INTERFACES += frmaddlevplats.ui
SOURCES += main.cpp
