######################################################################
# Automatically generated by qmake (1.04a) Wed Sep 10 10:21:37 2003
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += frmaddlevplats.ui.h
INTERFACES += frmaddlevplats.ui
SOURCES += main.cpp
