######################################################################
# Automatically generated by qmake (1.04a) Sat Nov 13 13:09:45 2004
######################################################################

TARGET=DSPAREW
DESTDIR+=/opt/olfix/bin
TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += frmdspartikelekonomidata.ui.h
INTERFACES += frmdspartikelekonomidata.ui
SOURCES += main.cpp
