######################################################################
# Automatically generated by qmake (1.04a) Sat Nov 15 20:03:06 2003
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += frmdspartikelekonomidata.ui.h
INTERFACES += frmdspartikelekonomidata.ui
SOURCES += main.cpp
