######################################################################
# Automatically generated by qmake (1.04a) Fri Dec 12 06:49:01 2003
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += frmdeltxt.ui.h
INTERFACES += frmdeltxt.ui
SOURCES += main.cpp
