######################################################################
# Automatically generated by qmake (1.04a) Sat Nov 13 11:27:50 2004
######################################################################

TARGET=DELTXTW
DESTDIR+=/opt/olfix/bin
TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += frmdeltxt.ui.h
INTERFACES += frmdeltxt.ui
SOURCES += main.cpp
